### ISSUE TITLE
Can't comment code in Gruntfile.js

### ISSUE THREAD

**Issue by alundiak** [ctf0/Seti_ST3#140]
I have recently installed Seti_UI theme. Configured, works fine.
But today, I realized I can't comment code out using command `Opt_Alt+Cmd+/` from keyboard (shortcut).
Using Menu navigation, I can **NOT also** do comment selected line or code block.
@ctf0 Any ideas?
UPD: I restarted Sublime a few times, even MacOS 10.10.3 restarted.

PS1. I can comment code in any other JavaScript file and in other files no matter of name and extension.
PS2. I have no such issue before Seti_UI usage.

**Comment by ctf0** [comment]
the answer https://github.com/ctf0/Seti_ST3/issues/95

**Comment by alundiak** [comment]
Ok @ctf0 please when u fix the code, close this issue. It will be sign for me to fetch latest code.

**Comment by ctf0** [comment]
there is nothing to fix, i mentioned the whole case in the other issue, and its basicly the way it is right now so u can have a different icon for gruntfile.js, to get it work as u expected just open it with javascript from the syntax list and ur problem is solved :).

**Comment by alundiak** [comment]
Sorry for my commenting here, but IMHO - Before Seti_UI everything was fine, and after I have bug. As a simple customer (not a developer in this case) I use plugin and I do obviously see the bug, which has been caused by plugin.
And besides, why icon for file should define if I can comment code inside of file or not. Why? If there is file extension ".js" which visually tells me it's JavaScript file.
Please explain me any reason why icon for file should describe Sublime behavior regarding the file?

PS. Yes, when I even changed syntax to JavaScript manually, on demand, it works - I can comment. But I have to do all the time, when I have new opening of file in SubLime. What a heck?

**Comment by ctf0** [comment]
it seems u didnt read the other issue ,so anyway here is a copy/paste of the explanation

> 
i think i know why
because with the latest update ,if u noticed the Gruntfile.js now have a new icon and not the normal js ,and for that we had to tinker with the language files so ur Gruntfile.js is now being recognized as a something else other than JS even if u still get the syntax HL of the JS ,
>
as a solution try to set that file to always be opened with JavaScript and see if it work.
also plz report back whether the icon has changed to js or remained the same ?

**Comment by alundiak** [comment]
Still, don't get it - why icon should define behavior of text editor referring to some exact file type/extension? Is this some kind of "good development practice"? 
Btw, the same is with `gulpfile.js`. Both of them are the same files in content as other js files. if so, icon defines behavior, why json files with dedicated icon are ok - I can use `Opt+Cmd+/`.
U have to admit, it's bug. And suggested workaround is not appropriate way to follow, IMHO.

**Comment by ctf0** [comment]
>
and for that we had to tinker with the language files so ur Gruntfile.js is now being recognized as a something else other than JS even if u still get the syntax HL of the JS 

does this make any sense ???

**Comment by alundiak** [comment]
Yes, it does. But i don't like it. Anyway will wait for next updates from
plugin.

On Thursday, June 4, 2015, Muah <notifications@github.com> wrote:

> and for that we had to tinker with the language files so ur Gruntfile.js
> is now being recognized as a something else other than JS even if u still
> get the syntax HL of the JS
>
> does this make any sense ???
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ctf0/Seti_ST3/issues/140#issuecomment-108909051>.
>


-- 
Sent from Gmail Mobile

**Comment by ctf0** [comment]
maybe i would come up with a solution later but currently i will leave it as it is.

**Comment by ctf0** [comment]
@kim3er i understand your frustration, can you send me this file you are having this issue with to test on from my end ?

**Comment by kim3er** [comment]
Here is a video demonstrating the issue. I've managed to replicate this on multiple `gulpfile.js` and `gulpfile.babel.js` files.

https://www.dropbox.com/s/aocv353ybpzh17q/Gulpfile.mov?dl=0

**Comment by kim3er** [comment]
I should add, that I appreciate the effort to differentiate between types of JS files. I'm surprised there isn't a better way to inherit from existing syntax/bindings in ST3.

**Comment by ctf0** [comment]
thanks for the video, again plz send me the file to test with from my end.

**Comment by kim3er** [comment]
Sorry, I wasn't being difficult. I'm just not sure which file you'd like me to send.

If you're referring to the `gulpfile.babel.js`, I've managed to replicate the functionality on multiple files of the same name. There is nothing special about the specific file (hence the video).

If you're referring to the TMLanguage file, which I suspect you're not. My SETI_UI package is up to date (I think, quickly checks...)

If the issue is that you don't have immediate access to a Gulp powered project, let me know and I'll se up a dummy on in a repo.

**Comment by ctf0** [comment]
send me gulpfile.js you are trying to set to JS and not working

**Comment by kim3er** [comment]
Here is an example file. https://www.dropbox.com/s/dvslayq3t2dbjcv/gulpfile.js?dl=0

ST3 appears to remember the overridden syntax (the context menu is correctly ticked), but the file still opens using the original `Gulpfile JS` syntax.

**Comment by ctf0** [comment]
right now am using ST 3095 and what i found is
- the file is opened with the HL of JS syntax while the name in the bottom right corner says `Gulpfile JS`
- the file by default is ticked at the `open all with current...` as javascript even if at the standard list its not.

so right now if your issue was that the HL is not working as standard JS, from my end i can see other wise.
and if your issue was that the syntax standard list is showing the file as Gulpfile rather than JS, sorry i have no solution for that.

**Comment by kim3er** [comment]
Thanks for looking into this @ctf0, it's very much appreciated. Changing the last line of **Gulpfile JS.tmLanguage** worked!

Are their any negative side effects to this change, that you're aware of? Is it worth me submitting a pull request for the change?

**Comment by ctf0** [comment]
nah its okay, if the icon is still working then everything is okay, you can send me the request.
