### ISSUE TITLE
Cannot find how to increase sidebar icon width

### ISSUE THREAD

**Issue by plopinou** [ctf0/Seti_ST3#191]
I've changed the font size up to 15px because my eyes are quite tired and everything's too small with a 2560x1440 resolution. Unfortunately, changing the font size increases the icons height, but not their width, deforming them vertically.
I've found how to change the folder icons (content_margin of the icon_folder class in Seti.sublime-theme), but I cannot find the setting for the file type ones. I suppose this is independent for each extension and in the corresponding .tmPreferences file, but what to put in their ?

Any help would be greatly appreciated.

Thank you for your work on this nice theme.

**Comment by ctf0** [comment]
i understand the eye tiredness am also having the same, however changing the file icon size is related to the image it self and because ST works with images not with svg like ATOM so you have 2 sizes either standard for resolution or retina, 

anyway as an answer just open the images without the `@2x` and scale the image up, not the width/height but the image it self.

**Comment by ctf0** [comment]
there is a setting u can modify in the theme that allow controlling the icon size, however again as ST use images not svg so playing with those settings makes the image pixelate :(.
