### ISSUE TITLE
Cursor width

### ISSUE THREAD

**Issue by panczarny** [ctf0/Seti_ST3#237]
Hi, how can I make cursor not so bold? It's not cool for me.

**Comment by ctf0** [comment]
u mean `caret_extra_width` ?

**Comment by panczarny** [comment]
Yes, I didn't notice this setting.
Sorry for unnecessary issue!

**Comment by AlexVentura** [comment]
I have my `caret_extra_width`property set to `10` and it looks pretty for me like a rectangle.
Now, how can I make it to replace the letter which is being highlighted by the cursor?

As in the images below, I want to replace the number `1` for any other character I press, because it is being highlighted by rectangle cursor as you can see.

<img width="254" alt="screen shot 2016-05-06 at 11 48 07 am" src="https://cloud.githubusercontent.com/assets/13169164/15079893/d2474d68-1380-11e6-8913-a71b65062600.png">

<img width="293" alt="screen shot 2016-05-06 at 11 47 51 am" src="https://cloud.githubusercontent.com/assets/13169164/15079907/e60b9174-1380-11e6-8b48-ad2dec84335e.png">

**Comment by ctf0** [comment]
@AlexVentura this is out of the theme scope, however the cursor in ST not the same as the one in the terminal, both have different behavior.
