### ISSUE TITLE
files with .coffee extension doesn't have icons

### ISSUE THREAD

**Issue by PombaM** [ctf0/Seti_ST3#284]
OS: Ubuntu 16.04.1 LTS
Sublime Text 3, Build 3126

My setting:

```javascript
{
	"Seti_accent": true,
	"Seti_alt_tree_row": true,
	"Seti_panel_nrml": true,
	"Seti_sb_tree_miny": true,
	"Seti_show_group_arrows": true,
	"Seti_tabs_small": true,
	"Seti_top_heading_small": true,
	"theme": "Seti_orig.sublime-theme"
}
```

![screenshot from 2016-10-24 08-38-19](https://cloud.githubusercontent.com/assets/11157420/19632409/e362be0e-99c5-11e6-9cdc-70c45f9a3adc.png)

**Comment by ctf0** [comment]
am using https://packagecontrol.io/packages/Better%20CoffeeScript and all is good

**Comment by PombaM** [comment]
I am using the same package for CoffeeScript, this issue is not about syntax highlighting, but icon not showing up in the sidebar.

**Comment by ctf0** [comment]
well, the second i installed the package the icon showd up, which means its not related to the syntax package nor the theme rather its something else that took over the coffee icon pref.

i would recommend remove seti & any other theme u have, clear the cache, re-install seti again and test.

**Comment by PombaM** [comment]
Yea, i did clear by `~/.config/sublime-text-3/ ` directory, reinstall sublime and installed this theme, its working! Must be something wrong in my config or something.

**Comment by oivva** [comment]
This is related to the theme. Because of `icons/Langs` & `icons/Prefs` folders. If the user installs two or more custom themes they conflicts each other, that's why `coffee` icon is missing. More details [here](https://forum.sublimetext.com/t/sublime-text-3-file-icons-in-sidebar/21134/4).

That's why I've created [zz File Icons](https://github.com/oivva/st-file-icons) to reduce conflicts and provide all icon settings in one place. You can [add support](https://github.com/oivva/st-file-icons#bring-support-to-your-theme) of it. Currently it supported by `Boxy Theme` & `Material Theme`.

**Comment by PombaM** [comment]
@oivva I have used your excellent `zz File Icons` along with [Spacegray](http://kkga.github.io/spacegray/) with no issue whatsoever even though it isn't "supported" :smile:

**Comment by oivva** [comment]
"Supported" means you can use icons provided by the package or by the theme. If theme doesn't support `zz File Icons` it just overrides the icons provided by the theme, so you can use icons from the package only.

**Comment by ctf0** [comment]
@oivva lets be clear that i can only speak for what this theme can & cant do, using another theme that use the same prefs/settings as seti is definitely out of my scope, also keep in mind that all the themes that use custom icons are derived from Seti and not the other way around so i believe the issue is more related to the other themes & not this one.  

also having a one centralized package that have support for icons wont be possible for more than one reason: 
* not every theme have the same file support ex. (laravel artisan, laravel echo, lock file) which its up to the theme maker to add or not in which case Seti.
* every theme maker colors the icons the way he/she sees fits to its theme.
* its not easy to change/edit the icons colors once they are made "programmatically speaking"

and so to fix that ST will have to do something similar to what **Atom** have which i dont think is one of ST team priorities atm.

**Comment by oivva** [comment]
@ctf0,

>  lets be clear that i can only speak for what this theme can & cant do, using another theme that use the same prefs/settings as seti is definitely out of my scope, also keep in mind that all the themes that use custom icons are derived from Seti and not the other way around so i believe the issue is more related to the other themes & not this one.

I'm fully agree with you. But currently the centralized storage the best possible option. `zz File Icons` do not provide icons when you have `.st-file-icons` file in the `*.sublime-theme` directory it provides only preferences.

> not every theme have the same file support ex. (laravel echo, lock file, etc...) which its up to the theme maker to add or not in which case Seti.

I'm working on that. So if theme doesn't include some icons they will be replaced with icons provided by the `zz File Icons`.

> every theme maker colors the icons the way he/she sees fits to its theme.

Yes of course, the plugin provides only the preferences if your theme supports it, so the only thing you need to do, just remove icon prefs & rename icon pngs. Guidelines are only for embedded icons, not for yours.

> its not easy to change/edit the icons colors once they are made "programmatically speaking" and here is a proof equinusocio/material-theme#917

It's easy to change icon colors if you have white monochrome icons. In that case [your code](https://github.com/equinusocio/material-theme/issues/917#issuecomment-250086942) do the job.

**Comment by ctf0** [comment]
i still believe the best solution would be for ST to stick to the package settings instead of moving them all to the general scope but again as this is more of a hack rather than an actual api design then we just have to wait for them to come up with something solid to fix this once and for all.

however on a side note, if you want ur package to be truly fix the icons issue, i would suggest that it search for all icons folders and removes/backup them according to each theme and only keep the icons from ur package available, this way no matter what theme the user install he still get the same experience without any conflict between packages & if user wants to stick to the icons that come with the theme then ur package will then restore those icons and disable it self.

**Comment by oivva** [comment]
> however on a side note, if you want ur package to truly fix the icons issue, i would suggest that it search for all icons folders and removes/backup them according to each theme and only keep the icons from ur package available

It's not possible if theme has no `.no-sublime-package` :disappointed:

**Comment by ctf0** [comment]
np, the package can extract the theme `.sublime-package` file into the `Packages` folder and it will work just the same

**Comment by oivva** [comment]
Nope, even if we remove settings from the extracted theme, settings from the theme's sublime-package will be used. However I've found another solution how to resolve conflicts, I'll introduce it in December.

**Comment by ctf0** [comment]
actually no, the packages folder over-ride anything in the installed-packages

**Comment by oivva** [comment]
No, it doesn't. Just tried) It overrides only files, not the extracted folder. So if you remove file from the extracted folder it will be used file from the package.

**Comment by ctf0** [comment]
thats because its cached, u will need to clear the cache aswell
