### ISSUE TITLE
To many updates on master branch

### ISSUE THREAD

**Issue by safjanowski** [ctf0/Seti_ST3#94]
Is there possible to make less updates on master branch?

It is annoying to run SublimeText and restart it because there was update in template.
I have a little suggestion – you can develop updates in another branch and merge that branch to master one time per month.

It is strange to update version from 1.0 to 7.x in 3 months. Are you going to have the same version as Chrome to the end of 2015?

**Comment by ctf0** [comment]
hahaha ,ofcourse not ,but don't worry the update will be less from now on as most of the intended functionally is in place.

on a side not, u don't need to restart ST eveytime a new update comes up ,because ur theme is already cached ,so u just continue ur work normally and next time u open ST the new updated will be cached.
