### ISSUE TITLE
Conflicts with Sublimetext Codeformatte

### ISSUE THREAD

**Issue by numediaweb** [ctf0/Seti_ST3#95]
I opened an issue there too, please check [Formatter for this file type (seti_ui) not found](https://github.com/akalongman/sublimetext-codeformatter/issues/131)

**Comment by ctf0** [comment]
with which file u r getting this problem ?

**Comment by numediaweb** [comment]
Gruntfile.js

**Comment by ctf0** [comment]
i think i know why
because with the latest update ,if u noticed the `Gruntfile.js` now have a new icon and not the normal js ,and for that we had to tinker with the language files so ur `Gruntfile.js` is now being recognized as a something else other than JS even if u still get the syntax HL of the JS ,

as a solution try to set that file to always be opened with `JavaScript` and see if it work.
also plz report back whether the icon has changed to `js` or remained the same ?

**Comment by numediaweb** [comment]
Thanks for the hint!
I changed it to javascript and the formatted now recognizes it and also I have the Grunt icon attached to the file :)

**Comment by alundiak** [comment]
Guys, I can't comment any code inside of Gruntfile.js, is this related to above u discussed?
`Alt+Cmd+/` just does nothing.
PS. I recently installed **Seti_UI** theme, but before, I had no such issue.

**Comment by ctf0** [comment]
@alundiak yes its related to the above.
