### ISSUE TITLE
Color scheme looks bad in pair with Sublime EasyMotion plugin

### ISSUE THREAD

**Issue by tytskiy** [ctf0/Seti_ST3#98]
Hello, could you take a look and fix this kind of highlighting. 
As for me it looks barely readable.

Additions: 

https://github.com/tednaleid/sublime-EasyMotion

![image](https://cloud.githubusercontent.com/assets/2727037/6127601/956c6c6a-b135-11e4-8bfd-ef8a256d4daa.png)

**Comment by ctf0** [comment]
which color version u r using ?

**Comment by tytskiy** [comment]
As per my settings: 

`"color_scheme": "Packages/User/SublimeLinter/Seti (SL).tmTheme",`

But to be correct i tried 

`"color_scheme": "Packages/Seti_UI/Scheme/Seti.tmTheme",`

and it looks the same.

Also i renamed ticket to be more consistent.

**Comment by ctf0** [comment]
first u need to update ur release because SL support was added a while ago.
second that color is not a bad render its simply the scope that EM use which is `entity.name.class` 
so go to ur `/packages/user/` and create new file `EasyMotion.sublime-settings` and paste this into it 
```
{
    "jump_target_scope" : "constant.numeric",
}
```
or change the scope to whatever u like.
